app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('set_lang','Wp_omissionController@set_lang');
Route::get('set_omission','Wp_omissionController@set_omission');
Route::get('/delete_file/{id}', 'Wp_omissionController@delete_file');
Route::get('/set_calendar', 'Wp_omissionController@set_calendar');
Route::get('/get_calendars', 'Wp_omissionController@get_calendars');

Route::get('/logo/{id}', 'Wp_omissionController@logo');
Route::get('/article/{id}', 'Wp_omissionController@article');
Route::get('/web/{id}', 'Wp_omissionController@web');
Route::get('/web_development/{id}', 'Wp_omissionController@web_development');
Route::get('/social_media/{id}', 'Wp_omissionController@social_media');
Route::get('/suite/{id}', 'Wp_omissionController@suite');
Route::get('/infographic/{id}', 'Wp_omissionController@infographic');
Route::get('/developer/{id}', 'Wp_omissionController@developer');



Route::post('/create_card', 'Wp_omissionController@create_card');
Route::post('/update_card', 'Wp_omissionController@update_card');
Route::post('/delete_card', 'Wp_omissionController@delete_card');

Route::post('/create_section', 'Wp_omissionController@create_section');
Route::post('/update_section', 'Wp_omissionController@update_section');
Route::post('/delete_section', 'Wp_omissionController@delete_section');


Route::post('/set_calendar_image', 'Wp_omissionController@set_calendar_image');
Route::post('/save_file', 'Wp_omissionController@save_file');
Route::post('/save_file_html', 'Wp_omissionController@save_file_html');
Route::post('/delete_file_ajax', 'Wp_omissionController@delete_file_ajax');
Route::post('/save_omission', 'Wp_omissionController@save_omission');


Route::resource("wp_omissions","Wp_omissionController");
Route::resource("wp_omissions_files","Wp_omissions_fileController");
Route::resource("wp_omissions_styles","Wp_omissions_styleController");
Route::resource("wp_omissions_calendars","Wp_omissions_calendarController");

Route::get('/', array('as' => 'wp_omissions.index', 'uses' => 'Wp_omissionController@index'));
//Route::get('/home', array('as' => 'ogrowthmissions.index', 'uses' => 'OgrowthmissionController@index'));

app/Wp_omissions_file.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Imagine\Image\Box;
use Imagine\Image\ImageInterface;
use Orchestra\Imagine\Facade as Imagine;

class Wp_omissions_file extends Model
{
    //
	
	public static function create_thumbnail($path, $filename, $extension)
	{
	    $width  = 100;
	    $height = 100;
	    $mode   = ImageInterface::THUMBNAIL_OUTBOUND;
	    $size   = new Box($width, $height);

	    $thumbnail   = Imagine::open("{$path}/{$filename}.{$extension}")->thumbnail($size, $mode);
	    $destination = "{$filename}.thumb.{$extension}";

	    $thumbnail->save("{$path}/{$destination}");
	}
	
	
	public static function create_mockup($path, $filename, $extension)
	{
	    $width  = 900;
	    $height = 900;
	    $mode   = ImageInterface::THUMBNAIL_OUTBOUND;
	    $size   = new Box($width, $height);

	    $thumbnail   = Imagine::open("{$path}/{$filename}.{$extension}")->thumbnail($size, $mode);
	    $destination = "{$filename}.mockup.{$extension}";

	    $thumbnail->save("{$path}/{$destination}");
	}
	
}

app/Http/Controllers/Wp_omissions_fileController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Wp_omissions_file;
use App\Wp_omissions_style;
use Log;
use Illuminate\Http\Request;

use Imagine\Image\Box;
use Imagine\Image\ImageInterface;
use Orchestra\Imagine\Facade as Imagine;

class Wp_omissions_fileController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$wp_omissions_files = Wp_omissions_file::orderBy('id', 'desc')->paginate(10);
		$viewsw = "my_missions";
		return view('wp_omissions_files.index', compact('wp_omissions_files','viewsw'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{	$viewsw = "my_missions";
		return view('wp_omissions_files.create',compact('viewsw'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$wp_omissions_file = new Wp_omissions_file();

		$wp_omissions_file->title = $request->input("title");
        $wp_omissions_file->section = $request->input("section");
		$wp_omissions_file->omission_id = $request->input("omission_id");
		$wp_omissions_file->updated_view = $request->input("updated_view");
		
		$updated_view = $request->input("updated_view");
			
		if($request->file('file')!= ""){

			Log::info('Entro en guardar archivo');
			$file = $request->file('file');
	        $destinationPath = 'files/'.$request->input("omission_id");
	        $extension = $file->getClientOriginalExtension();
			$fileName_solo = md5(uniqid(rand(), true));
	        $fileName = $fileName_solo . '.' . $extension;
	        $upload_success = $file->move($destinationPath, $fileName);
			
			$wp_omissions_file->file = $fileName_solo;
			$wp_omissions_file->extension = $extension;
			
			Wp_omissions_file::create_thumbnail($destinationPath, $fileName_solo, $extension);
			
			if($wp_omissions_file->section == "mockup"){
				Wp_omissions_file::create_mockup($destinationPath, $fileName_solo, $extension);
			}
			
		}

		$wp_omissions_file->save();
		
		return redirect()->action('Wp_omissionController@edit', ['id' => $wp_omissions_file->omission_id,'updated_view' => $updated_view]);
		//return redirect()->route('wp_omissions.edit', $wp_omissions_file->omission_id)->with('message', 'Item updated successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{	$viewsw = "my_missions";
		$wp_omissions_file = Wp_omissions_file::findOrFail($id);

		return view('wp_omissions_files.show', compact('wp_omissions_file','viewsw'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{	$viewsw = "my_missions";
		$wp_omissions_file = Wp_omissions_file::findOrFail($id);

		return view('wp_omissions_files.edit', compact('wp_omissions_file','viewsw'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$wp_omissions_file = Wp_omissions_file::findOrFail($id);

		$wp_omissions_file->title = $request->input("title");
        $wp_omissions_file->file = $request->input("file");
        $wp_omissions_file->section = $request->input("section");

		$wp_omissions_file->save();

		return redirect()->route('wp_omissions_files.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$wp_omissions_file = Wp_omissions_file::findOrFail($id);
		$wp_omissions_file->delete();

		return redirect()->route('wp_omissions_files.index')->with('message', 'Item deleted successfully.');
	}
	
	function create_thumbnail($path, $filename, $extension)
	{
	    $width  = 320;
	    $height = 320;
	    $mode   = ImageInterface::THUMBNAIL_OUTBOUND;
	    $size   = new Box($width, $height);

	    $thumbnail   = Imagine::open("{$path}/{$filename}.{$extension}")->thumbnail($size, $mode);
	    $destination = "{$filename}.thumb.{$extension}";

	    $thumbnail->save("{$path}/{$destination}");
	}

}

resources/views/wp_omissions_files/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Wp_omissions_files / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('wp_omissions_files.store') }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ old("title") }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                  
                    <div class="form-group @if($errors->has('section')) has-error @endif">
                       <label for="section-field">Section</label>
                    <input type="text" id="section-field" name="section" class="form-control" value="{{ old("section") }}"/>
                       @if($errors->has("section"))
                        <span class="help-block">{{ $errors->first("section") }}</span>
                       @endif
                    </div>
					
		            <div class="form-group" id="file">
		              <label for="file_name">Mission image</label>
	                  <input type="file" id="file-field" name="file">
		            </div>
					
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('wp_omissions_files.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/wp_omissions_files/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Wp_omissions_files / Edit #{{$wp_omissions_file->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('wp_omissions_files.update', $wp_omissions_file->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
				

                <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ $wp_omissions_file->title }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('file')) has-error @endif">
                       <label for="file-field">File</label>
                    <input type="text" id="file-field" name="file" class="form-control" value="{{ $wp_omissions_file->file }}"/>
                       @if($errors->has("file"))
                        <span class="help-block">{{ $errors->first("file") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('section')) has-error @endif">
                       <label for="section-field">Section</label>
                    <input type="text" id="section-field" name="section" class="form-control" value="{{ $wp_omissions_file->section }}"/>
                       @if($errors->has("section"))
                        <span class="help-block">{{ $errors->first("section") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('wp_omissions_files.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/wp_omissions_files/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Wp_omissions_files
            <a class="btn btn-success pull-right" href="{{ route('wp_omissions_files.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($wp_omissions_files->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>TITLE</th>
                        <th>FILE</th>
                        <th>SECTION</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($wp_omissions_files as $wp_omissions_file)
                            <tr>
                                <td>{{$wp_omissions_file->id}}</td>
                                <td>{{$wp_omissions_file->title}}</td>
                    <td>{{$wp_omissions_file->file}}</td>
                    <td>{{$wp_omissions_file->section}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('wp_omissions_files.show', $wp_omissions_file->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('wp_omissions_files.edit', $wp_omissions_file->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('wp_omissions_files.destroy', $wp_omissions_file->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $wp_omissions_files->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/wp_omissions_files/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Wp_omissions_files / Show #{{$wp_omissions_file->id}}</h1>
        <form action="{{ route('wp_omissions_files.destroy', $wp_omissions_file->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('wp_omissions_files.edit', $wp_omissions_file->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="title">TITLE</label>
                     <p class="form-control-static">{{$wp_omissions_file->title}}</p>
                </div>
                    <div class="form-group">
                     <label for="file">FILE</label>
                     <p class="form-control-static">{{$wp_omissions_file->file}}</p>
                </div>
                    <div class="form-group">
                     <label for="section">SECTION</label>
                     <p class="form-control-static">{{$wp_omissions_file->section}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('wp_omissions_files.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection