app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('set_lang','Wp_omissionController@set_lang');
Route::get('set_omission','Wp_omissionController@set_omission');
Route::get('/delete_file/{id}', 'Wp_omissionController@delete_file');
Route::get('/set_calendar', 'Wp_omissionController@set_calendar');
Route::get('/get_calendars', 'Wp_omissionController@get_calendars');

Route::get('/logo/{id}', 'Wp_omissionController@logo');
Route::get('/article/{id}', 'Wp_omissionController@article');
Route::get('/web/{id}', 'Wp_omissionController@web');
Route::get('/web_development/{id}', 'Wp_omissionController@web_development');
Route::get('/social_media/{id}', 'Wp_omissionController@social_media');
Route::get('/suite/{id}', 'Wp_omissionController@suite');
Route::get('/infographic/{id}', 'Wp_omissionController@infographic');
Route::get('/developer/{id}', 'Wp_omissionController@developer');



Route::post('/create_card', 'Wp_omissionController@create_card');
Route::post('/update_card', 'Wp_omissionController@update_card');
Route::post('/delete_card', 'Wp_omissionController@delete_card');

Route::post('/create_section', 'Wp_omissionController@create_section');
Route::post('/update_section', 'Wp_omissionController@update_section');
Route::post('/delete_section', 'Wp_omissionController@delete_section');


Route::post('/set_calendar_image', 'Wp_omissionController@set_calendar_image');
Route::post('/save_file', 'Wp_omissionController@save_file');
Route::post('/save_file_html', 'Wp_omissionController@save_file_html');
Route::post('/delete_file_ajax', 'Wp_omissionController@delete_file_ajax');
Route::post('/save_omission', 'Wp_omissionController@save_omission');


Route::resource("wp_omissions","Wp_omissionController");
Route::resource("wp_omissions_files","Wp_omissions_fileController");
Route::resource("wp_omissions_styles","Wp_omissions_styleController");
Route::resource("wp_omissions_calendars","Wp_omissions_calendarController");

Route::get('/', array('as' => 'wp_omissions.index', 'uses' => 'Wp_omissionController@index'));
//Route::get('/home', array('as' => 'ogrowthmissions.index', 'uses' => 'OgrowthmissionController@index'));

app/Wp_omissions_calendar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wp_omissions_calendar extends Model
{
    //
}

app/Http/Controllers/Wp_omissions_calendarController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Wp_omissions_calendar;
use Illuminate\Http\Request;

class Wp_omissions_calendarController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$wp_omissions_calendars = Wp_omissions_calendar::orderBy('id', 'desc')->paginate(10);

		return view('wp_omissions_calendars.index', compact('wp_omissions_calendars'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('wp_omissions_calendars.create');
		
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$wp_omissions_calendar = new Wp_omissions_calendar();

		$wp_omissions_calendar->start_date = $request->input("start_date");
        $wp_omissions_calendar->social_network = $request->input("social_network");
        $wp_omissions_calendar->content = $request->input("content");
        $wp_omissions_calendar->link = $request->input("link");
        $wp_omissions_calendar->file = $request->input("file");
        $wp_omissions_calendar->omission_id = $request->input("omission_id");
		
		

		$wp_omissions_calendar->save();
		
		return redirect()->route('wp_omissions_calendars.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$wp_omissions_calendar = Wp_omissions_calendar::findOrFail($id);

		return view('wp_omissions_calendars.show', compact('wp_omissions_calendar'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$wp_omissions_calendar = Wp_omissions_calendar::findOrFail($id);

		return view('wp_omissions_calendars.edit', compact('wp_omissions_calendar'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$wp_omissions_calendar = Wp_omissions_calendar::findOrFail($id);

		$wp_omissions_calendar->start_date = $request->input("start_date");
        $wp_omissions_calendar->social_network = $request->input("social_network");
        $wp_omissions_calendar->content = $request->input("content");
        $wp_omissions_calendar->link = $request->input("link");
       // $wp_omissions_calendar->omission_id = $request->input("omission_id");
		
		if($request->file('file')!= ""){
			
			$file = $request->file('file');
	        // SET UPLOAD PATH
	        $destinationPath = 'ocalendars';
	         // GET THE FILE EXTENSION
	        $extension = $file->getClientOriginalExtension();
	         // RENAME THE UPLOAD WITH RANDOM NUMBER
	        $fileName = rand(11111, 99999) . '.' . $extension;
	         // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY
	        $upload_success = $file->move($destinationPath, $fileName);
			$wp_omissions_calendar->file = $fileName;
		}
		$viewsw = "my_missions";
		$wp_omissions_calendar->save();
		
		return redirect()->route('wp_omissions.edit', $wp_omissions_calendar->omission_id)->with('message', 'Item updated successfully.');

	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$wp_omissions_calendar = Wp_omissions_calendar::findOrFail($id);
		$wp_omissions_calendar->delete();

		return redirect()->route('wp_omissions_calendars.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/wp_omissions_calendars/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Wp_omissions_calendars / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('wp_omissions_calendars.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('start_date')) has-error @endif">
                       <label for="start_date-field">Start_date</label>
                    <input type="text" id="start_date-field" name="start_date" class="form-control" value="{{ old("start_date") }}"/>
                       @if($errors->has("start_date"))
                        <span class="help-block">{{ $errors->first("start_date") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('social_network')) has-error @endif">
                       <label for="social_network-field">Social_network</label>
                    <input type="text" id="social_network-field" name="social_network" class="form-control" value="{{ old("social_network") }}"/>
                       @if($errors->has("social_network"))
                        <span class="help-block">{{ $errors->first("social_network") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <textarea class="form-control" id="content-field" rows="3" name="content">{{ old("content") }}</textarea>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('link')) has-error @endif">
                       <label for="link-field">Link</label>
                    <input type="text" id="link-field" name="link" class="form-control" value="{{ old("link") }}"/>
                       @if($errors->has("link"))
                        <span class="help-block">{{ $errors->first("link") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('file')) has-error @endif">
                       <label for="file-field">File</label>
                    <textarea class="form-control" id="file-field" rows="3" name="file">{{ old("file") }}</textarea>
                       @if($errors->has("file"))
                        <span class="help-block">{{ $errors->first("file") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('omission_id')) has-error @endif">
                       <label for="omission_id-field">Omission_id</label>
                    <input type="text" id="omission_id-field" name="omission_id" class="form-control" value="{{ old("omission_id") }}"/>
                       @if($errors->has("omission_id"))
                        <span class="help-block">{{ $errors->first("omission_id") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('wp_omissions_calendars.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/wp_omissions_calendars/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Wp_omissions_calendars / Edit #{{$wp_omissions_calendar->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('wp_omissions_calendars.update', $wp_omissions_calendar->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('start_date')) has-error @endif">
                       <label for="start_date-field">Start_date</label>
                    <input type="text" id="start_date-field" name="start_date" class="form-control" value="{{ $wp_omissions_calendar->start_date }}"/>
                       @if($errors->has("start_date"))
                        <span class="help-block">{{ $errors->first("start_date") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('social_network')) has-error @endif">
                       <label for="social_network-field">Social_network</label>
                    <input type="text" id="social_network-field" name="social_network" class="form-control" value="{{ $wp_omissions_calendar->social_network }}"/>
                       @if($errors->has("social_network"))
                        <span class="help-block">{{ $errors->first("social_network") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <textarea class="form-control" id="content-field" rows="3" name="content">{{ $wp_omissions_calendar->content }}</textarea>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('link')) has-error @endif">
                       <label for="link-field">Link</label>
                    <input type="text" id="link-field" name="link" class="form-control" value="{{ $wp_omissions_calendar->link }}"/>
                       @if($errors->has("link"))
                        <span class="help-block">{{ $errors->first("link") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('file')) has-error @endif">
                       <label for="file-field">File</label>
                    <textarea class="form-control" id="file-field" rows="3" name="file">{{ $wp_omissions_calendar->file }}</textarea>
                       @if($errors->has("file"))
                        <span class="help-block">{{ $errors->first("file") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('omission_id')) has-error @endif">
                       <label for="omission_id-field">Omission_id</label>
                    <input type="text" id="omission_id-field" name="omission_id" class="form-control" value="{{ $wp_omissions_calendar->omission_id }}"/>
                       @if($errors->has("omission_id"))
                        <span class="help-block">{{ $errors->first("omission_id") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('wp_omissions_calendars.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/wp_omissions_calendars/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Wp_omissions_calendars
            <a class="btn btn-success pull-right" href="{{ route('wp_omissions_calendars.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($wp_omissions_calendars->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>START_DATE</th>
                        <th>SOCIAL_NETWORK</th>
                        <th>CONTENT</th>
                        <th>LINK</th>
                        <th>FILE</th>
                        <th>OMISSION_ID</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($wp_omissions_calendars as $wp_omissions_calendar)
                            <tr>
                                <td>{{$wp_omissions_calendar->id}}</td>
                                <td>{{$wp_omissions_calendar->start_date}}</td>
                    <td>{{$wp_omissions_calendar->social_network}}</td>
                    <td>{{$wp_omissions_calendar->content}}</td>
                    <td>{{$wp_omissions_calendar->link}}</td>
                    <td>{{$wp_omissions_calendar->file}}</td>
                    <td>{{$wp_omissions_calendar->omission_id}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('wp_omissions_calendars.show', $wp_omissions_calendar->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('wp_omissions_calendars.edit', $wp_omissions_calendar->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('wp_omissions_calendars.destroy', $wp_omissions_calendar->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $wp_omissions_calendars->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/wp_omissions_calendars/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Wp_omissions_calendars / Show #{{$wp_omissions_calendar->id}}</h1>
        <form action="{{ route('wp_omissions_calendars.destroy', $wp_omissions_calendar->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('wp_omissions_calendars.edit', $wp_omissions_calendar->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="start_date">START_DATE</label>
                     <p class="form-control-static">{{$wp_omissions_calendar->start_date}}</p>
                </div>
                    <div class="form-group">
                     <label for="social_network">SOCIAL_NETWORK</label>
                     <p class="form-control-static">{{$wp_omissions_calendar->social_network}}</p>
                </div>
                    <div class="form-group">
                     <label for="content">CONTENT</label>
                     <p class="form-control-static">{{$wp_omissions_calendar->content}}</p>
                </div>
                    <div class="form-group">
                     <label for="link">LINK</label>
                     <p class="form-control-static">{{$wp_omissions_calendar->link}}</p>
                </div>
                    <div class="form-group">
                     <label for="file">FILE</label>
                     <p class="form-control-static">{{$wp_omissions_calendar->file}}</p>
                </div>
                    <div class="form-group">
                     <label for="omission_id">OMISSION_ID</label>
                     <p class="form-control-static">{{$wp_omissions_calendar->omission_id}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('wp_omissions_calendars.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection