app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('set_lang','Wp_omissionController@set_lang');
Route::get('set_omission','Wp_omissionController@set_omission');
Route::get('/delete_file/{id}', 'Wp_omissionController@delete_file');
Route::get('/set_calendar', 'Wp_omissionController@set_calendar');
Route::get('/get_calendars', 'Wp_omissionController@get_calendars');

Route::get('/logo/{id}', 'Wp_omissionController@logo');
Route::get('/article/{id}', 'Wp_omissionController@article');
Route::get('/web/{id}', 'Wp_omissionController@web');
Route::get('/web_development/{id}', 'Wp_omissionController@web_development');
Route::get('/social_media/{id}', 'Wp_omissionController@social_media');
Route::get('/suite/{id}', 'Wp_omissionController@suite');
Route::get('/infographic/{id}', 'Wp_omissionController@infographic');
Route::get('/developer/{id}', 'Wp_omissionController@developer');



Route::post('/create_card', 'Wp_omissionController@create_card');
Route::post('/update_card', 'Wp_omissionController@update_card');
Route::post('/delete_card', 'Wp_omissionController@delete_card');

Route::post('/create_section', 'Wp_omissionController@create_section');
Route::post('/update_section', 'Wp_omissionController@update_section');
Route::post('/delete_section', 'Wp_omissionController@delete_section');


Route::post('/set_calendar_image', 'Wp_omissionController@set_calendar_image');
Route::post('/save_file', 'Wp_omissionController@save_file');
Route::post('/save_file_html', 'Wp_omissionController@save_file_html');
Route::post('/delete_file_ajax', 'Wp_omissionController@delete_file_ajax');
Route::post('/save_omission', 'Wp_omissionController@save_omission');


Route::resource("wp_omissions","Wp_omissionController");
Route::resource("wp_omissions_files","Wp_omissions_fileController");
Route::resource("wp_omissions_styles","Wp_omissions_styleController");
Route::resource("wp_omissions_calendars","Wp_omissions_calendarController");

Route::get('/', array('as' => 'wp_omissions.index', 'uses' => 'Wp_omissionController@index'));
//Route::get('/home', array('as' => 'ogrowthmissions.index', 'uses' => 'OgrowthmissionController@index'));

app/Wp_omissions_style.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wp_omissions_style extends Model
{
    //
}

app/Http/Controllers/Wp_omissions_styleController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Wp_omissions_style;
use Illuminate\Http\Request;

class Wp_omissions_styleController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$wp_omissions_styles = Wp_omissions_style::orderBy('id', 'desc')->paginate(30);
		$viewsw = "styles";
		return view('wp_omissions_styles.index', compact('wp_omissions_styles','viewsw'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{	$viewsw = "styles";
		return view('wp_omissions_styles.create',compact('viewsw'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$wp_omissions_style = new Wp_omissions_style();

		$wp_omissions_style->es = $request->input("es");
        $wp_omissions_style->en = $request->input("en");
       
        $wp_omissions_style->description_en = $request->input("description_en");
		$wp_omissions_style->description_es = $request->input("description_es");
		
	   if($request->file("file")!= ""){
		
		$file = $request->file("file");
        // SET UPLOAD PATH
        $destinationPath = 'styles';
         // GET THE FILE EXTENSION
        $extension = $file->getClientOriginalExtension();
         // RENAME THE UPLOAD WITH RANDOM NUMBER
        $fileName = rand(11111, 99999) . '.' . $extension;
         // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY
        $upload_success = $file->move($destinationPath, $fileName);
		$wp_omissions_style->file = $fileName;
		
	   }

		$wp_omissions_style->save();

		return redirect()->route('wp_omissions_styles.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$wp_omissions_style = Wp_omissions_style::findOrFail($id);
		$viewsw = "styles";
		return view('wp_omissions_styles.show', compact('wp_omissions_style','viewsw'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$wp_omissions_style = Wp_omissions_style::findOrFail($id);
		$viewsw = "styles";
		return view('wp_omissions_styles.edit', compact('wp_omissions_style','viewsw'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$wp_omissions_style = Wp_omissions_style::findOrFail($id);

		$wp_omissions_style->es = $request->input("es");
        $wp_omissions_style->en = $request->input("en");
       
        $wp_omissions_style->description_en = $request->input("description_en");
		$wp_omissions_style->description_es = $request->input("description_es");
		
 	   if($request->file("file")!= ""){
		
 		$file = $request->file("file");
         // SET UPLOAD PATH
         $destinationPath = 'styles';
          // GET THE FILE EXTENSION
         $extension = $file->getClientOriginalExtension();
          // RENAME THE UPLOAD WITH RANDOM NUMBER
         $fileName = rand(11111, 99999) . '.' . $extension;
          // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY
         $upload_success = $file->move($destinationPath, $fileName);
 		$wp_omissions_style->file = $fileName;
		
 	   }

		$wp_omissions_style->save();

		return redirect()->route('wp_omissions_styles.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$wp_omissions_style = Wp_omissions_style::findOrFail($id);
		$wp_omissions_style->delete();

		return redirect()->route('wp_omissions_styles.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/wp_omissions_styles/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h3><i class="glyphicon glyphicon-plus"></i> Wp_omissions_styles / Create </h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('wp_omissions_styles.store') }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('es')) has-error @endif">
                       <label for="es-field">Es</label>
                    <input type="text" id="es-field" name="es" class="form-control" value="{{ old("es") }}"/>
                       @if($errors->has("es"))
                        <span class="help-block">{{ $errors->first("es") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('en')) has-error @endif">
                       <label for="en-field">En</label>
                    <input type="text" id="en-field" name="en" class="form-control" value="{{ old("en") }}"/>
                       @if($errors->has("en"))
                        <span class="help-block">{{ $errors->first("en") }}</span>
                       @endif
                    </div>
                    
                    <div class="form-group">
                       <label for="description-field">Description Español</label>
                    <textarea class="form-control" id="description_es-field" rows="3" name="description_es">{{ old("description_es") }}</textarea>
                  
                    </div>
					
					
                    <div class="form-group">
                       <label for="description-field">Description Ingles</label>
                    <textarea class="form-control" id="description_en-field" rows="3" name="description_en">{{ old("description_en") }}</textarea>
                    </div>
					
		   		    <div class="row">

		    	        <div class="col-md-6">
			
		                     <input type="file" id="file-field" name="file">
		   	            </div>

		   			 </div>
					 
					 <br /><br />
					
				<div class="row">	
                <div class="col-md-12">
                    <button type="submit" class="form-control button-next btn btn-info addfiles">Create</button>
          
                </div>
				</div>
            </form>

        </div>
    </div>
@endsection

resources/views/wp_omissions_styles/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Wp_omissions_styles / Edit #{{$wp_omissions_style->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('wp_omissions_styles.update', $wp_omissions_style->id) }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('es')) has-error @endif">
                       <label for="es-field">Es</label>
                    <input type="text" id="es-field" name="es" class="form-control" value="{{ $wp_omissions_style->es }}"/>
                       @if($errors->has("es"))
                        <span class="help-block">{{ $errors->first("es") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('en')) has-error @endif">
                       <label for="en-field">En</label>
                    <input type="text" id="en-field" name="en" class="form-control" value="{{ $wp_omissions_style->en }}"/>
                       @if($errors->has("en"))
                        <span class="help-block">{{ $errors->first("en") }}</span>
                       @endif
                    </div>
                    
                    <div class="form-group">
                       <label for="description-field">Description Español</label>
                    <textarea class="form-control" id="description_es-field" rows="3" name="description_es">{{ $wp_omissions_style->description_es }}</textarea>
                  
                    </div>
					
					
                    <div class="form-group">
                       <label for="description-field">Description Ingles</label>
                    <textarea class="form-control" id="description_en-field" rows="3" name="description_en">{{ $wp_omissions_style->description_en }}</textarea>
                    </div>
					
		   		    <div class="row">

		    	        <div class="col-md-6">
			
		                     <input type="file" id="file-field" name="file">
		   	            </div>

		   			 </div>
					 
					 <br /><br />
					
				<div class="row">	
                <div class="col-md-12">
                    <button type="submit" class="form-control button-next btn btn-info addfiles">Update</button>
          
                </div>
				</div>
            </form>

        </div>
    </div>
@endsection

resources/views/wp_omissions_styles/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
		
		 <a class="btn btn-success pull-right" href="{{ route('wp_omissions_styles.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
		
        <h3>
           Web Styles
           
        </h3>
		
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($wp_omissions_styles->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>ES</th>
                        <th>EN</th>
                        <th>FILE</th>
                       
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($wp_omissions_styles as $wp_omissions_style)
                            <tr>
                                <td>{{$wp_omissions_style->id}}</td>
                                <td>{{$wp_omissions_style->es}}
								<br />Descripcion:<br /> 
								{{$wp_omissions_style->description_es}}
								</td>
                    <td>{{$wp_omissions_style->en}}
					<br />Description: <br />
					{{$wp_omissions_style->description_en}}
					</td>
                    <td>
					<img src="/styles/{{$wp_omissions_style->file}}" alt="Mountain View" style="width:304px;height:228px;">
					</td>
                    
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('wp_omissions_styles.show', $wp_omissions_style->id) }}">View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('wp_omissions_styles.edit', $wp_omissions_style->id) }}">Edit</a>
                                    <form action="{{ route('wp_omissions_styles.destroy', $wp_omissions_style->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $wp_omissions_styles->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/wp_omissions_styles/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Wp_omissions_styles / Show #{{$wp_omissions_style->id}}</h1>
        <form action="{{ route('wp_omissions_styles.destroy', $wp_omissions_style->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('wp_omissions_styles.edit', $wp_omissions_style->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="es">ES</label>
                     <p class="form-control-static">{{$wp_omissions_style->es}}</p>
                </div>
                    <div class="form-group">
                     <label for="en">EN</label>
                     <p class="form-control-static">{{$wp_omissions_style->en}}</p>
                </div>
                    <div class="form-group">
                     <label for="file">FILE</label>
                     <p class="form-control-static">{{$wp_omissions_style->file}}</p>
                </div>
                    <div class="form-group">
                     <label for="description">DESCRIPTION</label>
                     <p class="form-control-static">{{$wp_omissions_style->description}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('wp_omissions_styles.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection